In [1]:
from os import path
import pandas as pd
import torch
from torch import nn
base = "/content/drive/MyDrive/NLP100/ch08"

fp_train = "70/train.csv"
df_train = pd.read_csv(path.join(base, fp_train), index_col=0)
df_train.head()

TITLE  ...       299
ID                                                         ...          
311098  RPT-Fitch Updates EMEA Consumer ABS Rating Cri...  ... -0.043620
49198   Gurlitt Wants to Return Nazi-Looted Art, Suedd...  ... -0.078003
410578  UPDATE 1-Fairfax Financial, CEO probed over po...  ... -0.030084
270668  Angelina Jolie - Angelina Jolie Will Not Tight...  ...  0.098994
301656  Patent Officials Cancel the Washington Redskin...  ...  0.029964

[5 rows x 307 columns]

In [2]:
X_train = torch.tensor(df_train[[str(r) for r in range(300)]].values.astype("float32"))
y_train = torch.tensor(df_train["CATEGORY"].values.astype("int"))
print(X_train[:5])
print(y_train[:5])

tensor([[-0.0013,  0.0379, -0.0267,  ...,  0.0854,  0.0412, -0.0436],
        [ 0.1195,  0.0482, -0.0516,  ..., -0.0930,  0.0493, -0.0780],
        [-0.0272,  0.0079, -0.0188,  ...,  0.0608,  0.0242, -0.0301],
        [ 0.0415,  0.0238, -0.1400,  ..., -0.0728, -0.0452,  0.0990],
        [ 0.0851,  0.0319,  0.1310,  ..., -0.0540,  0.0016,  0.0300]])
tensor([0, 2, 0, 2, 0])


In [3]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(300, 4, bias=False)
    self.softmax = nn.Softmax(dim=1)

  def forward(self, x):
    y = self.linear(x)
    y = self.softmax(y)
    return y

model = Model()
print(model)

Model(
  (linear): Linear(in_features=300, out_features=4, bias=False)
  (softmax): Softmax(dim=1)
)


In [4]:
loss_fn = nn.CrossEntropyLoss()
loss_1 = loss_fn(model(X_train)[0:1], y_train[0:1])
loss_1.backward()
grad_1 = model.linear.weight.grad

print("cross entropy loss")
print(loss_1)
print()
print("gradient")
print(grad_1)
print()

cross entropy loss
tensor(1.3994, grad_fn=<NllLossBackward>)

gradient
tensor([[ 2.3851e-04, -6.8749e-03,  4.8431e-03,  ..., -1.5516e-02,
         -7.4845e-03,  7.9204e-03],
        [-7.7324e-05,  2.2288e-03, -1.5701e-03,  ...,  5.0301e-03,
          2.4264e-03, -2.5678e-03],
        [-8.3183e-05,  2.3977e-03, -1.6891e-03,  ...,  5.4113e-03,
          2.6103e-03, -2.7623e-03],
        [-7.8002e-05,  2.2484e-03, -1.5839e-03,  ...,  5.0743e-03,
          2.4477e-03, -2.5903e-03]])



In [5]:
loss_4 = loss_fn(model(X_train)[0:4], y_train[0:4])
loss_4.backward()
grad_4 = model.linear.weight.grad
print("cross entropy loss")
print(loss_4)
print()
print("gradient")
print(grad_4)
print()

cross entropy loss
tensor(1.3875, grad_fn=<NllLossBackward>)

gradient
tensor([[ 0.0041, -0.0078,  0.0038,  ..., -0.0249, -0.0105,  0.0118],
        [ 0.0020,  0.0040, -0.0052,  ...,  0.0047,  0.0035, -0.0034],
        [-0.0081, -0.0003,  0.0066,  ...,  0.0155,  0.0035, -0.0049],
        [ 0.0020,  0.0041, -0.0052,  ...,  0.0047,  0.0035, -0.0034]])

